site_name: Nova Regna wiki
site_description: This be that there Nova Regna worldbuilding project
site_url: https://wiki.kitabe.link
repo_url: https://github.com/QuickFastly/Nova-Regna
repo_name: QuickFastly/Nova-Regna
edit_uri: ""

theme:
    name: 'material'
    logo: assets/meta/flowericon.png
    favicon: assets/meta/flowericon.png
    custom_dir: overrides
    font:
        text: Exo
        code: Red Hat Mono
    language: en
    palette:
    
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    features:
        - navigation.indexes
        - navigation.top
        - navigation.tabs
        - navigation.expand
        - search.suggest
        - search.highlight
        
# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search
  - ezlinks:
        wikilinks: true
  - mermaid2
  - awesome-pages
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - callouts
  - git-revision-date-localized:
        type: date
        fallback_to_build_date: true
        locale: en
  - mkdocs-simple-hooks:
      hooks:
        on_env: "overrides.hooks.on_env:on_env"
        on_page_markdown: "overrides.hooks.on_page_markdown:on_page_markdown"
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - meta-descriptions
extra_javascript:
  - assets/js/mathjax.js
  - assets/js/utils.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/tooltipster.bundle.js  
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - assets/css/template/blog.css
    - assets/css/template/grid.css
    - assets/css/template/img-grids-float.css
    - assets/css/template/tooltipster.bundle.min.css
    - assets/css/template/utils.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css
extra:
  generator: false
  blog_list:
    pagination: true
    pagination_message: true
    pagination_translation: 'posts in'
  hooks:
    strip_comments: true
    fix_heading: false
